name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build
      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run tests
      - name: Run Tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Deploy to hosting service (e.g., GitHub Pages, Netlify, Vercel, etc.)
      # Replace the following lines with your deployment script or command
      - name: Deploy to Hosting Service
        run: |
          # Add your deployment command here
          echo "Deploying to hosting service..."
